# workflow의 이름 
name: CI

# 해당 workflow가 언제 실행될 것인지에 대한 트리거 지정
on:
  push:
    branches: [ master ] # master branch로 push될 때 실행
  pull_request:
    branches: [ master ] # master branch로 pr될때 실행

# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있다.
jobs:
  build:
    name: CI
    # 해당 jobs 에서 아래의 steps 들이 어떠한 환경에서 실행될 것인지를 지정
    runs-on: ubuntu-latest

    steps:
    # 작업에서 액세스할 수 있도록 $GITHUB_WORKSPACE에서 저장소를 체크아웃
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

    # application.properties를 프로젝트에 포함
      - name: add Application.properties
        run:
          touch ./src/main/resources/application.properties
        shell: bash

      - name: copy Application.properties
        run:
          echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
        shell: bash

    # gradle 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
  

